language: node_js
node_js:
- node
- '8'
before_script:
- npm install -g gulp-cli
deploy:
  provider: npm
  email: samni698@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: samuelnilsson/lossy-music-mirror
