language: node_js
node_js:
- '10'
- '9'
- '8'
after_script:
- npm run coveragereport
before_deploy:
- npm run compile
deploy:
  provider: npm
  email: samni698@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: samuelnilsson/lossy-music-mirror
    node: '10'
  on:
    branch: release/*
    repo: samuelnilsson/lossy-music-mirror
    node: '10'
